# Generated by Django 3.0.2 on 2020-01-20 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200119_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.date(2020, 1, 20)),
        ),
    ]
